### ISSUE TITLE
Artifacts rendering fonts and textures

### ISSUE THREAD

**Issue by ibancg** [albertoruibal/jmini3d#1]
See the images attached, taken with a Samsung GT-I9000, API 10.
The second image belongs to the demo "Multiples cubes with a light".

![device-2014-12-31-002730](https://cloud.githubusercontent.com/assets/5263631/5584114/70a6370c-9084-11e4-9940-36f4339719c1.png)
![screenshot1944885161773139298](https://cloud.githubusercontent.com/assets/5263631/5584154/58aa1b4a-9085-11e4-8756-807793a34c88.png)

**Comment by albertoruibal** [comment]
Maybe that Nexus S does not support GL_LINEAR. I created a nexus_s branch changing GL_LINEAR by GL_NEAREST. Can you test if this branch fixes the artifacts? Thank you!

**Comment by ibancg** [comment]
Same problem.

**Comment by albertoruibal** [comment]
It seems that it only affects the Nexus S 2.3.x versions, I tested it remotely in a Nexus S 4G 4.1.2 and it works: https://appthwack.com/public/d6f0379c945ff4f19334e4788?view_mode=screenshots
