### ISSUE TITLE
How to add and remove Object3Ds from a scene?

### ISSUE THREAD

**Issue by kgilmer** [albertoruibal/jmini3d#5]
Hello, thanks for jmini3d!  I really like it.  I have a scene in which I would like to dynamically change a child (SkyboxGeometry).  However when running the change never takes effect.  I've tried using Scene.removeChild() and Scene.unload(), but neither has any effect on my scene.  How can I modify scene children dynamically?

**Comment by kgilmer** [comment]
I tried a different technique similar to the demo app, in which multiple scenes are rendered by the controller.  I am unable to get this working either.  The scene which contains the skybox does not render at all.  It is not a HUD scene as is in the demo.

Finally I tried swapping scenes that have different Skybox backgrounds.  The non-skybox Object3d's do change from scene to scene yet again the Skybox seems "stuck" on the first scene to render it.  There is something I'm missing about how to clean up Skybox objects between scenes...

**Comment by albertoruibal** [comment]
I tried it and it works for me, example in the NormalMapScene:

```
package jmini3d.demo;

import jmini3d.Color4;
import jmini3d.Object3d;
import jmini3d.Texture;
import jmini3d.Vector3;
import jmini3d.geometry.Geometry;
import jmini3d.geometry.PlaneGeometry;
import jmini3d.light.PointLight;
import jmini3d.material.PhongMaterial;

public class NormalMapScene extends ParentScene {
	PointLight pointLight;
	Object3d plane1;

	int counter = 0;

	public NormalMapScene() {
		super("Add and remove objects from scenes");

		Texture map = new Texture("wall.png");

		Color4 white = new Color4(255, 255, 255, 255);
		Color4 transparent = new Color4(0, 0, 0, 0);
		PhongMaterial material = new PhongMaterial(map, white, white, transparent);
		Geometry planeGeometry = new PlaneGeometry(1);

		plane1 = new Object3d(planeGeometry, material);
		plane1.setPosition(0, 0, 0);
		addChild(plane1);

		pointLight = new PointLight(new Vector3(0, 0, 0.5f), new Color4(128, 128, 128), 2);
		addLight(pointLight);
	}

	@Override
	public void update() {
		pointLight.position.setAllFrom(camera.getPosition());

		if (counter % 100 == 50) {
			//plane1.setVisible(false);
			removeChild(plane1);
		}

		if (counter % 100 == 99) {
			//plane1.setVisible(true);
			addChild(plane1);
		}
		counter++;
	}
}
```
There is also the option of Object3d::setVisible insted of removing the object
