### ISSUE TITLE
android demo upgraded

### ISSUE THREAD

**Issue by andresoviedo** [albertoruibal/jmini3d#6]
Hello there.  Thank you for sharing the code.
I had some issues compiling the android-demo.
So I had to create an Android project from scratch
and I imported the all needed files.

Just wanted to let you know that such fork is here :)
https://github.com/the3deers/jmini3d-demo-android

Kind regards

**Comment by albertoruibal** [comment]
Hello Andres!

Yes, it needed to update gradle, gradle tools and the android sdk. I just pushed a commit to the develop branch to make it work with the last  Android Studio:

https://github.com/mobialia/jmini3d/commit/af13d417bcc566f9766e7163e5e1d5fe9bba1770

I saw that your project is using travis: I'm a jenkins guy, but it is very interesting, I will study it.

Thank you!

**Comment by albertoruibal** [comment]
Now it is using JitPack
